Send the UDP packet to all resolved IP addresses
84codes/sparoid.js pull request #1
Opened 2021-07-28 15:07 UTC by dentarg

If given IP address as host, do not try to resolve it.

2021-07-28 16:08 UTC, carlhoerberg commented on src/sparoid.mjs
> +            resolver.setServers(["1.1.1.1", "8.8.8.8", "9.9.9.9"])
No possible to use the locally configured DNS resolvers?

2021-07-28 17:29 UTC, dentarg commented on src/sparoid.mjs
> +            resolver.setServers(["1.1.1.1", "8.8.8.8", "9.9.9.9"])
I didn't try, didn't think of it, added these seeing we add external servers in a few other projects.

what do we prefer?

2021-07-28 18:40 UTC, carlhoerberg commented
I think where you've seen that is when we use opendns to resolve our public
IP using their special record for that. Would prefer using the local DNS
when possible.

On Wed, 28 Jul 2021, 19:29 Patrik Ragnarsson, ***@***.***>
wrote:

> ***@***.**** commented on this pull request.
> ------------------------------
>
> In src/sparoid.mjs
> <https://github.com/84codes/sparoid.js/pull/1#discussion_r678511500>:
>
> > @@ -74,15 +77,30 @@ export default class Sparoid {
>          })
>      }
>
> -    udpSend(message) {
> +    resolvHost(host) {
> +        return new Promise((resolv, reject) => {
> +            if(net.isIPv4(host)) resolv([host])
> +            const resolver = new dns.Resolver()
> +            resolver.setServers(["1.1.1.1", "8.8.8.8", "9.9.9.9"])
>
> I didn't try, didn't think of it, added these seeing we add external
> servers in a few other projects.
>
> what do we prefer?
>
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub
> <https://github.com/84codes/sparoid.js/pull/1#discussion_r678511500>, or
> unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AABL6TWXECMCAPPH3FBFIHTT2A5AVANCNFSM5BER3HDQ>
> .
>

2021-07-28 18:43 UTC, dentarg commented
Sure

2021-07-28 19:03 UTC, dentarg commented
@carlhoerberg see the commit message for c5e59a855e23d9cb013fac5a668dd3884cb26b5f, as stated, not sure what's going on there...

2021-07-30 14:39 UTC, dentarg commented
Okay, I think https://github.com/84codes/sparoid.js/commit/0a3d0a722727d51d22f622298be6e47c5d0002a8 is a better version of this (no loop in `udpSend`) and I [shouldn't use `forEach`](https://stackoverflow.com/questions/37576685/using-async-await-with-a-foreach-loop)

2021-08-02 18:35 UTC, carlhoerberg requested changes

2021-08-02 18:35 UTC, carlhoerberg commented on src/sparoid.mjs
> +        }));
With `await` without `try/catch` rejections would be unhandled, I recommend: 

```suggestion
        await Promise.all(addresses.map((address) => self.udpSend(hmaced, address)));
```

Not sure if `self = this` is required anymore.

2021-08-02 18:35 UTC, carlhoerberg commented on src/sparoid.mjs
> +            if(net.isIPv4(host)) resolv([host])
```suggestion
            if (net.isIPv4(host)) resolv([host])
```

2021-08-02 21:33 UTC, dentarg commented on src/sparoid.mjs
> +        }));
> With `await` without `try/catch` rejections would be unhandled, I recommend

Thanks, I did that

> Not sure if `self = this` is required anymore.

It is, it is not working without it, we pass `self.host` as argument to `resolvHost()`

2021-08-02 21:36 UTC, carlhoerberg approved these changes

2021-08-02 21:36 UTC, merged